// Generated by https://quicktype.io
export interface LoginData {
    userName:   string;
    userPassword: string;
    userLanguage : string;
}

export interface RegisterData {
    correo:   string;
    password: string;
    nombre:   string;
}


export interface LoginResponse {
    usuario: Usuario;
    token:   string;
}

export interface LoginResponseGoingOut {
    tokenGoingOut:   string;
    status: Usuario;
    message: Usuario;
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    uid:    string;
    img?:   string;
}
